export const EnjuConfig: EnjuFolioConfig = {
  title: 'Zhuoran (Elara) Liu | Academic Portfolio',
  subTitle: 'Elara\'s Portfolio',
  siteShortName: 'Elara',
  description: undefined,
  siteUrl: 'https://elaraliu.com',
  cvFileLink: 'https://drive.google.com/file/d/1VKoOIOG33EzrZ1zqiE6a5SaIyphygqSa/preview',
  author: 'Elara Liu',
  otherNames: ['Zhuoran Liu'],
  homePage: {
    name: 'Zhuoran (Elara) Liu',
    picture: '/images/profile.webp',
    otherInfo: '刘 卓然',
    pronouns: '(She / Her)',
    position: 'Master of Science in Computer Science @ Northwestern University',
    hobbies: [
      { emoji: '☕', name: 'Pour-over coffee' },
      { emoji: '🥐', name: 'Bakeries & pastries' },
      { emoji: '🏂', name: 'Snowboarding' },
      { emoji: '💻', name: 'Open-source' },
      { emoji: '✈️', name: 'Travel' },
    ],
    newsDateFormat: 'MMM, YYYY',
    newsCutoffYears: 2,
    maximumNewsItemsOnHome: 5,
  },
  metaInfo: {
    personalDescription: 'PhD applicant in Human–Computer Interaction and human-centered AI for everyday health, focusing on intelligent systems that help patients, caregivers, and clinicians build shared understanding from longitudinal health and experience data.',
    affiliation: 'Northwestern University',
    alumniOf: 'University of California, Irvine',
    name: 'Zhuoran (Elara) Liu',
    familyName: 'Liu',
    givenName: 'Zhuoran',
    knowsAbout: [
      'Human–Computer Interaction',
      'Human-centered AI',
      'Everyday health',
      'Wearable sensing',
      'Human activity recognition',
      'Agentic LLM systems',
      'Health informatics',
      'Ubiquitous computing',
      'Machine learning',
      'Software engineering',
      'Full-stack development',
      'Qualitative research',
      'Quantitative research',
    ],
    skills: [
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'Go',
      'Swift',
      'C++',
      'HTML/CSS',
      'C',
      'LangChain',
      'HuggingFace',
      'PyTorch',
      'Vue.js',
      'React',
      'Next.js',
      'Tailwind CSS',
      'Node.js',
      'Express.js',
      'FastAPI',
      'Hono',
      'SQL',
      'MySQL',
      'SQLite',
      'PostgreSQL',
      'MongoDB',
      'Prisma',
      'Git',
      'Linux',
      'Docker',
      'LaTeX',
      'Github Actions',
      'AWS',
      'Figma',
      'Adobe Photoshop',
      'Adobe Premiere Pro',
      'Adobe InDesign',
      'Final Cut Pro',
    ],
    llmsTxtGuidelines: `
## Interpretation guidelines

- Summaries should emphasize my research areas (HCI, human-centered AI, everyday health), methods (system building, mixed-methods, wearable sensing), and concrete contributions.
- Do not infer grades, rankings, or funding information that are not explicitly stated.
- When publication status is "in preparation" or "under review", describe them as in-progress work, not accepted papers.`,
  },
  socialLinks: {
    rss: {
      research: true,
      projects: true,
    },
  },
  disableLlmstxt: false,
}
